---
title: "viz_IBD"
output: html_document
---


```{r, echo = FALSE}
# names of the demes in demes.txt (in order)
labels <- c("United Kingdom", "Spain", "Ireland", "Portugal", "Hungary", "Italy", "France", "Albania", 
            "Macedonia", "Belgium", "Switzerland", "Germany", "Croatia", "Bosnia", "Poland", "Czech Republic",
            "Serbia", "Netherlands", "Austria")

sims <- as.matrix(read.table("data/popres/popres_6_Inf_mean_sims.txt"))
rownames(sims) <- labels
colnames(sims) <- labels
```


```{r, echo = FALSE, eval = FALSE}
fit <- cmdscale(dist(sims), eig=TRUE, k =2)
x <- fit$points[,1]
y <- fit$points[,2]
plot(x, y, xlab="Coordinate 1", ylab="Coordinate 2", 
     main="Metric	MDS",	type="n")
text(x, y, labels = labels, cex=.7)
```

```{r include = FALSE}
library(corrplot)
library(igraph)
```

Let's do some PCA
```{r}

popres.pca <- prcomp(sims, center = TRUE, scale. = TRUE)
plot(popres.pca$x[,1], popres.pca$x[,2], type = "n", xlab = "PC1", ylab = "PC2")
text(popres.pca$x[,1], popres.pca$x[,2], labels = labels, cex=.7)
```


Let's visualize the similarity matrix on the log scale. Countries in the black squares cluster together (using hierarchical clustering)

```{r, echo = FALSE}
#raw_sims <- as.matrix(read.table("popres_lowerBnd_6_upperBnd_Inf.sims"))
#ipmap <- as.matrix(read.table("ipmap.txt"))
#rownames(raw_sims) <- substr(labels[ipmap], start = 1, stop = 2)
#colnames(raw_sims) <- substr(labels[ipmap], start = 1, stop = 2)
#fit <- cmdscale(dist(raw_sims), eig=TRUE, k =2)
#x <- fit$points[,1]
#y <- fit$points[,2]
#plot(x, y, xlab="Coordinate 1", ylab="Coordinate 2", 
#     main="Metric	MDS",	type="n")
#text(x, y, labels = substr(labels[ipmap], start = 1, stop = 2), cex=.7)

min2 <- min(sims[sims!=min(sims)])/2;
corr_sims <- sims+min2
#corr_sims <- log(sims+min2)
#diag(corr_sims) <- NA
is.na(corr_sims) <- do.call(cbind,lapply(corr_sims, is.infinite))
#corr_sims <- (corr_sims - min(corr_sims))/(max(corr_sims)-min(corr_sims))
#col3 <- colorRampPalette(c("red", "white", "blue"))
corrplot(corr = log(corr_sims)+max(abs(log(corr_sims))), diag=TRUE, order= "hclust", is.corr = FALSE, addrect = 3, method = "circle",cl.pos = "n")


#plot(1:length(diag(sims)), diag(sims), ylab = "within deme similarity", type = "n", xaxt = "n", xlab = "")
#text(1:length(diag(sims)), diag(sims), labels =  substr(labels, start=1, stop=3), cex = 0.7)

```


Let's visualize the similarity matrix in graph form (on the absolute scale)
```{r, echo=FALSE}
net=graph.adjacency(sims,mode="undirected",weighted=TRUE,diag=FALSE)
node.size <- 50*diag(sims)
plot.igraph(net,vertex.label=V(net)$name,layout=layout.fruchterman.reingold, edge.color="black",edge.width=5*E(net)$weight,
            vertex.size=node.size)
```