# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resistance_distance <- function(M) {
    .Call('rEEMSplots2_resistance_distance', PACKAGE = 'rEEMSplots2', M)
}

rcppcompute_Nm <- function(mtiles, mrates, mseeds, qtiles, qrates, qseeds, grandmean_m, grandmean_N, grandmean_Nm, marks, distm, weight, means_m, prGTx_m, prLTx_m, means_N, prGTx_N, prLTx_N, means_Nm, prGTx_Nm, prLTx_Nm) {
    invisible(.Call('rEEMSplots2_rcppcompute_Nm', PACKAGE = 'rEEMSplots2', mtiles, mrates, mseeds, qtiles, qrates, qseeds, grandmean_m, grandmean_N, grandmean_Nm, marks, distm, weight, means_m, prGTx_m, prLTx_m, means_N, prGTx_N, prLTx_N, means_Nm, prGTx_Nm, prLTx_Nm))
}

