// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// resistance_distance
Eigen::MatrixXd resistance_distance(const Eigen::MatrixXd& M);
RcppExport SEXP rEEMSplots2_resistance_distance(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type M(MSEXP);
    __result = Rcpp::wrap(resistance_distance(M));
    return __result;
END_RCPP
}
// rcppcompute_Nm
void rcppcompute_Nm(const Eigen::VectorXd& mtiles, const Eigen::VectorXd& mrates, const Eigen::MatrixXd& mseeds, const Eigen::VectorXd& qtiles, const Eigen::VectorXd& qrates, const Eigen::MatrixXd& qseeds, const double grandmean_m, const double grandmean_N, const double grandmean_Nm, const Eigen::MatrixXd& marks, const std::string& distm, const double weight, Eigen::VectorXd& means_m, Eigen::VectorXd& prGTx_m, Eigen::VectorXd& prLTx_m, Eigen::VectorXd& means_N, Eigen::VectorXd& prGTx_N, Eigen::VectorXd& prLTx_N, Eigen::VectorXd& means_Nm, Eigen::VectorXd& prGTx_Nm, Eigen::VectorXd& prLTx_Nm);
RcppExport SEXP rEEMSplots2_rcppcompute_Nm(SEXP mtilesSEXP, SEXP mratesSEXP, SEXP mseedsSEXP, SEXP qtilesSEXP, SEXP qratesSEXP, SEXP qseedsSEXP, SEXP grandmean_mSEXP, SEXP grandmean_NSEXP, SEXP grandmean_NmSEXP, SEXP marksSEXP, SEXP distmSEXP, SEXP weightSEXP, SEXP means_mSEXP, SEXP prGTx_mSEXP, SEXP prLTx_mSEXP, SEXP means_NSEXP, SEXP prGTx_NSEXP, SEXP prLTx_NSEXP, SEXP means_NmSEXP, SEXP prGTx_NmSEXP, SEXP prLTx_NmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mtiles(mtilesSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mrates(mratesSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type mseeds(mseedsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type qtiles(qtilesSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type qrates(qratesSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type qseeds(qseedsSEXP);
    Rcpp::traits::input_parameter< const double >::type grandmean_m(grandmean_mSEXP);
    Rcpp::traits::input_parameter< const double >::type grandmean_N(grandmean_NSEXP);
    Rcpp::traits::input_parameter< const double >::type grandmean_Nm(grandmean_NmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type marks(marksSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type distm(distmSEXP);
    Rcpp::traits::input_parameter< const double >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type means_m(means_mSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prGTx_m(prGTx_mSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prLTx_m(prLTx_mSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type means_N(means_NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prGTx_N(prGTx_NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prLTx_N(prLTx_NSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type means_Nm(means_NmSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prGTx_Nm(prGTx_NmSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type prLTx_Nm(prLTx_NmSEXP);
    rcppcompute_Nm(mtiles, mrates, mseeds, qtiles, qrates, qseeds, grandmean_m, grandmean_N, grandmean_Nm, marks, distm, weight, means_m, prGTx_m, prLTx_m, means_N, prGTx_N, prLTx_N, means_Nm, prGTx_Nm, prLTx_Nm);
    return R_NilValue;
END_RCPP
}
